name: Check Omada Versions on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  check-omada-versions:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: ["Beta", "Stable", "Dev"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Extract Version and Set Tag
        id: extract_version
        run: |
          VERSION_HA=$(yq '.version' "Omada ${{ matrix.target }}/config.yaml")
          VERSION_OMADA=$(echo $VERSION_HA | sed -E 's/-ha[0-9]+$//')
          echo "VERSION_OMADA=$VERSION_OMADA" >> $GITHUB_ENV
          echo "Target ${{ matrix.target }} VERSION_OMADA: $VERSION_OMADA"

      - name: Check Omada Version Availability
        uses: ./.github/actions/version-checks
        with:
          version: "${{ env.VERSION_OMADA }}"
